// <auto-generated />
namespace Project4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changedb17032021 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedb17032021));
        
        string IMigrationMetadata.Id
        {
            get { return "202103170735397_change-db-17032021"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
